

dim = [6,7]
PADDING_X = 30
PADDING_Y = 20
CHIP_DIAMETER = 50
CHIP_PADDING = 15
WIDTH = PADDING_X*2 + dim[1]*CHIP_DIAMETER + (dim[1]-1)*CHIP_PADDING
HEIGHT = PADDING_Y*2 + dim[0]*CHIP_DIAMETER + (dim[0]-1)*CHIP_PADDING
CONTROL_HEIGHT = 100
COLOR_P1 = 'yellow'
COLOR_P2 = 'red'
BOARD_COLOR = 'blue'
BACKGROUND_COLOR = 'white'
